### ISSUE TITLE
[Ajout données] Durée de participation

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-essais-cliniques#100]
Dans l'issue #74, la donnée "Durée de la participation à l'essai clinique" avait été identifiée comme potentiellement native R4 via `Group.characteristic.period`.
Cette durée de participation est fixe pour une cohorte, elle indique combien de temps cette cohorte est impliquée dans l'essai.

L'utilisation de `Group.characteristic.period` ne semble pas adaptée puisqu'il s'agit de la période lié à une caractéristique et non pas au groupe en général.
Aucun élément natif (en R4 ou en R5) ne semble correspondre à cette donnée, est-ce qu'on créé une extension ?

**Comment by audreyMoisan** [comment]
la demande durée de la participation à l'essai clinique était une demande de santé.fr. formulée par les utilisateurs. Effectivement  si on veut coller à la réalité scientifique et technique d'un essai clinique alors la durée de participation est liée à une cohorte. 
Si on se regarde clinical trials voilà ce qu'on a : 
<img width="988" alt="Capture d’écran 2023-11-28 à 11 44 33" src="https://github.com/ansforge/IG-fhir-essais-cliniques/assets/130970408/1ce92b1a-0ec6-4555-8c5c-30dd82a14aa9">

Pour moi le time frame qui est précisé dans un outcome est une information différente de la durée de participation à l'essai clinique. (dans le cas de ce time frame, je comprends qu'il s'agit de la fenêtre de temps afin de voir l'effet du traitement) 
Pour la durée de participations nous avons deux options : 
- Soit cela fait partie de la description liée au groupe et dans ce cas c'est une information parmi un descriptif plus global 
- Soit on décide de créer un champ spécifique sur la durée de participation et on aurait quelque chose comme cela : 
       - Group / cohorte intitulé 
       - Descriptif 
       - Durée de la participation

**Comment by sly-kereval** [comment]
Si je comprends bien, en termes FHIR : 
- Option 1 : Créer une extension au niveau de ResearchStudy
- Option 2 : Utiliser l'élément natif arm et ajouter une extension pour la période 
![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/125375447/6c66b3c7-79d2-4b6b-9c12-7d43fa5fafb4)

**Comment by sly-kereval** [comment]
La proposition retenue est d'utiliser l'élément natif arm et d'ajouter une extension pour la durée de participation. 

Preview disponible : https://ansforge.github.io/IG-fhir-essais-cliniques/ig/ajout-donnees-mapping/mapping.html

**Comment by sdemeyANS** [comment]
Concernant ce point
> 
> * [ ]  Valider le type de données pour la durée de participation

A discuter lors du point hebdo je pense

**Comment by sdemeyANS** [comment]
réunion du 29/01
mettre durée dans description

**Comment by paulineheurtebise** [comment]
Réunion 15/02 : 
Valider dans la descirption. 
Impact IG : à mettre dans le short 
Impact mapping : à ne pas afficher
