### ISSUE TITLE
Demande santé.fr : champs non trouvés dans le mapping

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-fhir-essais-cliniques#101]
## Description du problème
Je retransmets une question PO Santé.fr pour le traçabilité des demandes sur l'IG
certains champs non trouvés dans le mapping FHIR:
"
- Description : pas trouvé dans le mapping FHIR
- Sujet : Est-ce l'attribut sujet concerné = condition ou Domaine thérapeutique = TherapeuticArea ?
- Nombre de participants
- Critères : En regardant le mapping FIHR, critères vient de la classe Group ? Mélangée avec âge et genre ?
- Volontaires sains acceptés : Pas trouvé dans le mapping

"

**Comment by audreyMoisan** [comment]
En réponse à votre question : 
- Description : ce champ n'est pas encore crée sur le SIRIPH2G et il n'existe pas non plus dans le CTIS. Nous pouvons créer le champ mais il sera vide pour le moment. 
- Sujet, la question n'est pas claire. Domaine thérapeutique = therapeutic Area (qui est mappé seul) 
condition = pathologie. Condition étant le mot en anglais. La pathologie est renseignée seulement pour les essais CTIS pour le moment (champ à créer sur le SIRIPH2G) en ce qui concerne le domaine thérapeutique l'information est renseignée sur toutes les régulations. Health condition est bien mappé dans sujet. 
- Nombre de participants : = sample size (dans participants) -c'est une référence c'est surement pour cela que c'est difficile pour la PO à trouver 
- Critères : je ne comprends pas la question, cela fait référence aux critères d'inclusion. Effectivement l'âge et le genre correspondent à des critères d'inclusion. 
- volontaires sains : devrait correspondre à research study group (dans participants ) - mais on ne reçoit ce champ spécifique dans les données envoyée. Je pense que le SIRIPH2G ne parvient pas à récupérer cette valeur dans le CTIS

**Comment by sdemeyANS** [comment]
Merci @audreyMoisan :)
J'ai transmis

**Comment by sdemeyANS** [comment]
- pour description on a bien un élément prévu dans la ressource et dans le mapping il est mappé avec résumé de l'essai

<img width="347" alt="image" src="https://github.com/ansforge/IG-fhir-essais-cliniques/assets/117643165/ed89fb51-b897-4b28-ac0d-3177ccbd7fc9">

- pour sujet effectivement cela dépend de l'information attendue. Un exemple côté Santé.fr pourrait nous aider je pense
- pour participants dans Group "Effectif à recruter" ?
- pour critères oui c'est indiqué dans le mapping "Les critères (inclusion, exclusion, genre, âge, …) sont représentés par l’élément characteristic multivalué de la ressource Group via l’élément enrollment. Un critère correspond à un élément characteristic, qui possède un type, une valeur et un indicateur permettant de savoir s’il s’agit d’un critère d’inclusion ou d’exclusion." https://interop.esante.gouv.fr/ig/fhir/eclaire/mapping.html
- pour volontaires sains oui ce sera dans Group https://interop.esante.gouv.fr/ig/fhir/eclaire/StructureDefinition-eclaire-group.html

**Comment by sdemeyANS** [comment]
en complément l'xls de l'issue #74 peut aider je pense

**Comment by sdemeyANS** [comment]
en attente retour PO Santé.fr
