### ISSUE TITLE
[Ajout données] Date d'inscription au registre principal

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-essais-cliniques#105]
## Description du problème

Comment mapper la donnée Date of Registration in Primary Registry (Date d'inscription au registre principal) ?

## Fichier•s concerné•s

[mapping.txt](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images-source/mapping.txt)
[mappingResearchStudy.svg](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images/mappingResearchStudy.svg)
[ECLAIREResearchStudy.fsh](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/fsh/StructureDefinition/profiles/ECLAIREResearchStudy.fsh)

## Solution proposée

 Dans le profil ECLAIREResearchStudy l'élément identifier est slicé, avec un slice idPrimary qui correspond à l' identifiant primaire de l'essai clinique (Primary Registry and Trial Identifying Number). 
Est-ce que la donnée Date of Registration in Primary Registry est liée à cet identifiant ? 
Si oui, il est envisageable de la mapper sur identifier.period.start. Si non, la création d'une extension semble nécessaire.

**Comment by paulineheurtebise** [comment]
Suite échange 14/12 : 
Date de délivrance du numéro = date de délivrance du numéro, lié à l'organisme qui va le délivrer. 
Pour les numéros nationaux c'est l'ANSM, et d'autres organismes pour les numéros européens et internationaux.

**Comment by sly-kereval** [comment]
> Suite échange 14/12 : Date de délivrance du numéro = date de délivrance du numéro, lié à l'organisme qui va le délivrer. Pour les numéros nationaux c'est l'ANSM, et d'autres organismes pour les numéros européens et internationaux.

J'ai l'impression que cette précision colle avec l’utilisation de identifier.period.start puisque l'identifier a également un élément assigner.

**Comment by sly-kereval** [comment]
La proposition retenue est d'utiliser  identifier.period.start. 

Preview disponible : https://ansforge.github.io/IG-fhir-essais-cliniques/ig/ajout-donnees-mapping/mapping.html

**Comment by sdemeyANS** [comment]
taches à réaliser
- [ ] modification mapping
- [ ] ajouter définition (short) dans la SD
autres taches ?

**Comment by sdemeyANS** [comment]
cela me semble convenir vu que PEriod = Time period when id is/was valid for use
