### ISSUE TITLE
[Ajout données] Intervention / treatment

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-essais-cliniques#107]
## Description du problème

Comment mapper la donnée Intervention / treatment ?

Pour mapper cette donnée, il est nécessaire de connaître plus précisément les informations à véhiculer.

D'après l'xls de l'issue #74, il faudrait au moins 3 champs : 
![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/125375447/86906a41-6a2d-445d-be71-9866bbdef61b)

Est-ce que cette donnée est spécifique à une cohorte comme indiqué par le [WHO data set](https://www.who.int/clinical-trials-registry-platform/network/who-data-set) ?
![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/125375447/7ca77be0-520b-488c-9954-5fefcdee10bb)

## Fichier•s concerné•s

[mapping.txt](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images-source/mapping.txt)
[mappingResearchStudy.svg](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images/mappingResearchStudy.svg)
[ECLAIREResearchStudy.fsh](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/fsh/StructureDefinition/profiles/ECLAIREResearchStudy.fsh)

## Solution proposée

Pistes (à revoir selon les précisions apportées) : 
- si traitement du protocole à mettre dans le plandefinition du champ protocol proposée ici https://github.com/ansforge/IG-fhir-essais-cliniques/issues/74#issuecomment-1790907019
- voir ResearchStudy.comparisonGroup en R5
- extension complexe

**Comment by paulineheurtebise** [comment]
Suite échange 14/12 : 
il peut y a voir plusieurs bras (= arms, cohortes, groupe ou sous groupe). 
Recoit un ou plusieurs traitement spécifiques. 
Traitement : nom du traitement (texte + code si possible) , à quel bras c'est associé, key word
Renseigné dans le protocole de recherche actuellement. Pas complétement standardisé.

**Comment by sly-kereval** [comment]
> Suite échange 14/12 : il peut y a voir plusieurs bras (= arms, cohortes, groupe ou sous groupe). Recoit un ou plusieurs traitement spécifiques. Traitement : nom du traitement (texte + code si possible) , à quel bras c'est associé, key word Renseigné dans le protocole de recherche actuellement. Pas complétement standardisé.

Avec ces précisions, l'élément R5 comparisonGroup semble bien correspondre  :
![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/125375447/e1579080-e15a-4673-9b52-58a72b3c2a38)
Cependant, il est semble aussi possible d'utiliser l'élément protocol qui référence une ressource PlanDefinition dans laquelle il est possible de faire référence à une ressource Group via subject ou participant.

**Comment by sly-kereval** [comment]
La proposition retenue est d'utiliser l'élément arm (équivalent de comparisonGroup en R4) et de lui ajouter une extension pour le traitement.

Preview disponible : https://ansforge.github.io/IG-fhir-essais-cliniques/ig/ajout-donnees-mapping/mapping.html

**Comment by sdemeyANS** [comment]
que faudra-t-il mettre dans https://hl7.org/fhir/R4/researchstudy-definitions.html#ResearchStudy.arm.type ?
Intervention ce ne serait pas équivalent à intendedExposure en R5 ?

**Comment by sdemeyANS** [comment]
voir aussi comment https://github.com/ansforge/IG-fhir-essais-cliniques/issues/74#issuecomment-1790907019

**Comment by sly-kereval** [comment]
>  Intervention ce ne serait pas équivalent à intendedExposure en R5 ?

Ça semble correspondre en effet, à voir dans quels éléments on peut renseigner les informations dont on a besoin.

**Comment by paulineheurtebise** [comment]
Réunion 15/02 : 
Extension dans arm à créer. 
Choix d'une extension Intervention 0..* avec 2 sous éléments : 
nom (string) 0..1 + description (string) 0..1

Impact SD 
Impact Mapping 
Impact dev
