### ISSUE TITLE
[Ajout données] Study plan - design of the study

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-essais-cliniques#108]
## Description du problème

Comment mapper la donnée Study plan - design of the study ?

Les précisions suivantes sont apportées dans l'xls de l'issue #74.
![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/125375447/90403237-99c7-4f88-a51c-0005ec3ce32d)
Seuls les éléments de la section DESIGN DETAILS semblent correspondre à la donnée Study plan - design of the study, est-ce bien le cas ?

## Fichier•s concerné•s

[mapping.txt](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images-source/mapping.txt)
[mappingResearchStudy.svg](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images/mappingResearchStudy.svg)
[ECLAIREResearchStudy.fsh](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/fsh/StructureDefinition/profiles/ECLAIREResearchStudy.fsh)

## Solution proposée

L'élément primary purpose semble correspondre à l'élément FHIR ResearchStudy.primaryPurposeType.

Pour les autres éléments : 
- Proposition d'utiliser PlanDefinition du champ protocol https://github.com/ansforge/IG-fhir-essais-cliniques/issues/74#issuecomment-1790907019
  - Avantage : natif
  - Inconvénient : a priori pas de champs qui correspondent exactement aux éléments à mapper
 - Créer une extension complexe (+ voir studyDesign en R5)
   - Avantage : permet de définir exactement les éléments dont on a besoin et d'avoir les informations sans passer par une autre ressource
   - Inconvénient : pas natif

**Comment by paulineheurtebise** [comment]
Suite échange du 14/12 : 
Correspond à ce qui est renseigné dans le protocole de recherche. 
Composition/synthèse de différents éléments : intervention/traitement + outcomes measures

**Comment by sly-kereval** [comment]
A priori ces données sont contenues dans d'autres éléments : voir issues #107 et #112

**Comment by sdemeyANS** [comment]
du coup on prend protocol qui est natif en R4 c'est bien cela ?

**Comment by paulineheurtebise** [comment]
Réunion 15/02 : 
Study plan concaténation de données. 

Ajouter primaryPurpose dans le mapping. 
Pas de nécessité d'ajouter dans le mapping les éléments qui composent le study plan. 

Issues spécifiques pour Allocation + Interventional Model + Masking 
Mapping si besoin avéré.
