### ISSUE TITLE
[Ajout données] Brief summary

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-essais-cliniques#109]
## Description du problème

Comment mapper la donnée "Brief summary" ?

## Fichier•s concerné•s

[mapping.txt](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images-source/mapping.txt)
[mappingResearchStudy.svg](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images/mappingResearchStudy.svg)
[ECLAIREResearchStudy.fsh](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/fsh/StructureDefinition/profiles/ECLAIREResearchStudy.fsh)

## Solution proposée

Créer une extension à l'image de l'élément [descriptionSummary](http://hl7.org/fhir/R5/researchstudy-definitions.html#ResearchStudy.descriptionSummary) présent en R5

**Comment by audreyMoisan** [comment]
Cela semble correspondre à notre besoin pouvons nous valider cette solution lundi lors de notre échange.

**Comment by sly-kereval** [comment]
La proposition retenue est de créer une extension à l'image de descriptionSummary en R5.

Preview disponible : https://ansforge.github.io/IG-fhir-essais-cliniques/ig/ajout-donnees-mapping/mapping.html

**Comment by sdemeyANS** [comment]
utilisation extension r5
