### ISSUE TITLE
[Ajout données] Statut du recrutement

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-essais-cliniques#110]
## Description du problème

Comment mapper la donnée "Statut du recrutement" ?

Actuellement, l’élément natif FHIR ResearchStudy.status est utilisé pour mappé le statut de l'essai. 

En R5 :
- L'élément [status](http://hl7.org/fhir/R5/researchstudy-definitions.html#ResearchStudy.status) est toujours présent mais il ne correspond plus au statut de l'essai : 
![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/125375447/ff92c476-0ce9-44a2-b0e8-65af3c3d88fa)
- L'élément [progressStatus](http://hl7.org/fhir/R5/researchstudy-definitions.html#ResearchStudy.progressStatus) a été ajouté : 
![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/125375447/f8ab18d2-5ac6-4b8f-a501-c5ee765d8f1c)

Dans le valueset [Research Study Status](http://hl7.org/fhir/R5/valueset-research-study-status.html), required pour status en R4 et extensible pour progressStatus.state en R5, certaines valeurs sont liées au recrutement : 
- active-but-not-recruiting
- not-yet-recruiting
- recruiting

## Fichier•s concerné•s

[mapping.txt](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images-source/mapping.txt)
[mappingResearchStudy.svg](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images/mappingResearchStudy.svg)
[ECLAIREResearchStudy.fsh](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/fsh/StructureDefinition/profiles/ECLAIREResearchStudy.fsh)

**Comment by sly-kereval** [comment]
La proposition retenue est de créer une extension à l'image de progressStatus en R5 et de la slicer pour distinguer le statut de l'essai du statut du recrutement.

A valider : cardinalités

Impact : La donnée fonctionnelle statut de l'essai est déplacée de l'élément FHIR status vers la nouvelle extension progressStauts.

Preview disponible : https://ansforge.github.io/IG-fhir-essais-cliniques/ig/ajout-donnees-mapping/mapping.html

**Comment by sdemeyANS** [comment]
En R4 status restera quand même en 1..1 et on aura des valeurs qui sont reprises en R5 
<html>
<body>

active \| administratively-completed \| approved \| closed-to-accrual \| closed-to-accrual-and-intervention \| completed \| disapproved \| in-review \| temporarily-closed-to-accrual \| temporarily-closed-to-accrual-and-intervention \| withdrawn
--



</body>
</html>

Du coup pour state il faut aussi créer CS/VS et les définir sans doublon avec les valeurs de status non ?

**Comment by sdemeyANS** [comment]
du coup j'ai un doute pour la slice. A discuter

**Comment by sdemeyANS** [comment]
> Dans le valueset [Research Study Status](http://hl7.org/fhir/R5/valueset-research-study-status.html), required pour status en R4 et extensible pour progressStatus.state en R5, certaines valeurs sont liées au recrutement :
> 
> * active-but-not-recruiting
> * not-yet-recruiting
> * recruiting
> 

Du coup pourquoi ne pas oindiquer que le statut de recrutement est dans status de manière native?
Peut être qu'ajouter cela dans la définition de l'élément suffit?

**Comment by paulineheurtebise** [comment]
Réunion 15/02 : 
Extension statutRecrutement - attribut simple codé --> éviter la confusion progressStatut R5.
VS = "actif" + "terminé"
Impact SD 
Impact Mapping 
Impact Dev
