### ISSUE TITLE
[Ajout données] Publications about the study + Summary results

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-essais-cliniques#111]
## Description du problème

Comment mapper les données "Publications about the study" et "Summary results" ?

En R5 ces données semblent correspondre à l'élément [result](http://hl7.org/fhir/R5/researchstudy-definitions.html#ResearchStudy.result) : 
![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/125375447/797adcc0-cc3d-4099-aa8a-47e1243aedb2)
Cependant, les ressources EvidenceReport et Citation existent seulement à partir de la version R4B.

## Fichier•s concerné•s

[mapping.txt](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images-source/mapping.txt)
[mappingResearchStudy.svg](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images/mappingResearchStudy.svg)
[ECLAIREResearchStudy.fsh](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/fsh/StructureDefinition/profiles/ECLAIREResearchStudy.fsh)

## Solution proposée

Utiliser l'élément [relatedArtifact](http://hl7.org/fhir/R4/researchstudy-definitions.html#ResearchStudy.relatedArtifact) : 
![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/125375447/9e9c71c6-a95f-4583-be15-6d3783852e9c)

**Comment by sly-kereval** [comment]
La proposition retenue est d'utiliser l'élément relatedArtifact.

Preview disponible : https://ansforge.github.io/IG-fhir-essais-cliniques/ig/ajout-donnees-mapping/mapping.html

**Comment by sdemeyANS** [comment]
ok pour moi pour utiliser cet élément natif
