### ISSUE TITLE
[Ajout données] Conséquences principales et secondaires

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-essais-cliniques#112]
## Description du problème

Comment mapper la donnée "Conséquences principales (primary outcomes) + Conséquences secondaires (secondary outcomes) " ?

## Fichier•s concerné•s

[mapping.txt](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images-source/mapping.txt)
[mappingResearchStudy.svg](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/images/mappingResearchStudy.svg)
[ECLAIREResearchStudy.fsh](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/fsh/StructureDefinition/profiles/ECLAIREResearchStudy.fsh)

## Solution proposée

Créer un extension à l'image de l'élément R5 [outcomeMeasure](http://hl7.org/fhir/R5/researchstudy-definitions.html#ResearchStudy.outcomeMeasure) : 
![image](https://github.com/ansforge/IG-fhir-essais-cliniques/assets/125375447/d743a984-d859-4036-b357-8ef25ce4b0e1)

**Comment by audreyMoisan** [comment]
L'élément R5 semble convenir à la donnée conséquence principale pouvons nous valider cette solution lundi afin que nous puissions commencer les développements.

**Comment by sly-kereval** [comment]
La proposition retenue est de créer une extension à l’image de outcomeMeasure en R5.

Preview disponible : https://ansforge.github.io/IG-fhir-essais-cliniques/ig/ajout-donnees-mapping/mapping.html

**Comment by sdemeyANS** [comment]
A noter que en R5 il y a une réference à une ressource EvidenceVariable non utilisée à ce jour dans Eclaire et nous référencerons cette ressource en R4 https://hl7.org/fhir/R4/evidencevariable.html

**Comment by sdemeyANS** [comment]
> Proposition à valider : création d'une extension à l’image de outcomeMeasure en R5
> 
> Preview disponible : https://ansforge.github.io/IG-fhir-essais-cliniques/ig/ajout-donnees-mapping/mapping.html
> 
> Taches à réaliser :
> 
> * [x]  Modifier le mapping
> * [ ]  Créer l'extension ECLAIREOutcomeMeasure et l'ajouter dans la SD

il faudra aussi ajouter le CS et le VS pour type

**Comment by sdemeyANS** [comment]
extension comme pour EclaireLabel https://github.com/ansforge/IG-fhir-essais-cliniques/issues/94
