### ISSUE TITLE
Informations manquantes sur les contacts

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-essais-cliniques#32]
Le standard OMS demande des informations sur les contacts (scientifique et public) qu'il n’est pas possible de renseigner actuellement en FHIR, notamment l'adresse et l'affiliation.

**Comment by sly-kereval** [comment]
Actuellement les contacts sont mappés sur l'élément FHIR `contact` de type `ContactDetail` (éléments natifs `name` et `telecom`), avec un extension pour le type de contact (public ou scientifique).

Voici les infos demandés par le [standard OMS](https://www.who.int/clinical-trials-registry-platform/network/who-data-set) (points 7 et 8) et ce que nous proposons : 

- Informations demandées pour "Contact for Public Queries" & "Contact for Scientific Queries"
    - email address : contact.telecom
    - telephone number : contact.telecom 
    - postal address : extension (de type Address)

- Informations demandées uniquement pour "Contact for Scientific Queries"
Remarque : ici ils distinguent les informations requises selon 2 cas, "Principal Investigator" ou contact scientifique générique, à voir s'il faut prendre en compte cette distinction ou s'il faut juste pouvoir renseigner toutes les informations
    - affiliation : extension 
    - name : contact.name (Principal Investigator)
    - title : extension (Principal Investigator)

**Comment by sdemeyANS** [comment]
je préfère créer le moins d'extension possible pour être le plus intéropérable possible :)

**Comment by sly-kereval** [comment]
La partie narratif est mise à jour sur la branche [32-informations-manquantes-sur-les-contacts](https://github.com/ansforge/IG-essais-cliniques/tree/32-informations-manquantes-sur-les-contacts), la preview du mapping est disponible [ici](https://ansforge.github.io/IG-essais-cliniques/ig/32-informations-manquantes-sur-les-contacts/mapping.html).

Les extensions suivantes sont à créer : 
- ECLAIREContactAddress
- ECLAIREContactAffiliation
- ECLAIREContactName

**Comment by paulineheurtebise** [comment]
Weekly 18/09 : en cours de réalisation ANS/Kereval
