### ISSUE TITLE
Supprimer l'extension eclaire-condition-details

### ISSUE THREAD

**Issue by NerOcrO** [ansforge/IG-fhir-essais-cliniques#51]
Supprimer l'extension eclaire-condition-details qui ne semble pas ou plus être utile.

**Comment by sly-kereval** [comment]
Extrait du CR de l'atelier du 28/06/2023, concernant le sujet / la pathologie : 
* Actuellement, cette information n’est pas récupérée dans le SIRIPH2G car elle se trouve dans un document.
* Dans le CTIS, il y a un champ texte ouvert (obligatoire) pour indiquer la pathologie et éventuellement des précisons. --> 
* Un code MedDRA peut-être associé (optionnel) mais cette terminologie n’est pas utilisée par tout le monde. Actuellement, seul le code est récupéré.

Pour répondre à ce besoin, l'élément natif FHIR [condition](https://ansforge.github.io/IG-essais-cliniques/ig/main/StructureDefinition-eclaire-researchstudy-definitions.html#ResearchStudy.condition) est utilisé pour le code MedDRA, et l'extension [eclaire-condition-details](https://ansforge.github.io/IG-essais-cliniques/ig/main/StructureDefinition-eclaire-researchstudy-definitions.html#ResearchStudy.extension:eclaire-condition-details) a été créée pour le champ texte ouvert permettant d'indiquer la pathologie et éventuellement des précisions.

**Comment by NerOcrO** [comment]
Pour ce champs pathologie, on a simplifié comme ceci :

```
"condition": [
    {
      "coding": [
        {
          "display": "Locally-Advanced or Metastatic breast cancer (MBC)"
        }
      ],
      "text": "Disease Condition"
    },
    {
      "coding": [
        {
          "code": "10065430",
          "display": "HER2 positive breast cancer",
          "system": "http://terminology.hl7.org/CodeSystem/mdr",
          "version": "2.0.1"
        }
      ],
      "text": "MedDRA Condition"
    }
  ]
```
Le premier correspondant à la pathologie et le second à MedDra, est-ce ok pour vous ?

**Comment by sly-kereval** [comment]
Si je comprends bien, vous utilisez 2 instances de l'attribut `condition`, un pour le champ texte ouvert et un autre pour le code MedDRA, en utilisant le l'élement `text` pour les distinguer. Cela me semble problématique, surtout s'il y a plusieurs pathologies puisqu'il y aura 2 instances de l'attribut pour chaque pathologie, sans savoir lesquels sont liés.

**Comment by sly-kereval** [comment]
Précisions apportées lors du weekly du 05/09/2023 : 
Concernant le champ "disease condition", il s'agit d'un champ ouvert où le déposant peut écrire ce qu'il veut. Il peut donc renseigner plusieurs éléments (séparés par des virgules par exemple) mais le champ est récupéré tel quel sous forme de chaîne de caractère donc il ne peut pas y a voir plusieurs valeurs.  De plus, il s'agit d'une information différente du code MedDRA et non pas d'une information complémentaire.

**Comment by sly-kereval** [comment]
En regardant les sorties du swagger, j'ai l'impression que la même chose est faite pour l'élément category : 
![image](https://github.com/ansforge/IG-essais-cliniques/assets/125375447/91bf32a8-7499-4abd-828c-6eb99e6f6ed6)

**Comment by paulineheurtebise** [comment]
Ma compréhension du besoin : Indiquer la pathologie étudiée dans l'essai. 
Pour cela soit c'est un élément codé via MedDRA soit du texte provenant CTIS soit les deux ? 

**1.  Avec Extension ECLAIREConditionDetails**

Actuellement nous proposons élément codé dans "condition". 
Et le texte dans une extension ECLAIREConditionDetails.
L'intérêt de cette extension est de venir compléter "condition" avec un texte libre détaillé.
Je continue de préconiser cette solution. 

Exemple simplifié : 

> Extension ECLAIREConditionDetails = "Locally-Advanced or Metastatic breast cancer (MBC)"
condition = "10065430 - HER2 positive breast cancer"


**2.  Sans Extension ECLAIREConditionDetails**

Votre proposition est de tout mettre dans "condition" 
-> Ce que je peux comprendre puisque je pense qu'on désigne la même information qui est la pathologie étudiée. 
Cependant ces 2 informations n'ont pas le même type de donnée et je pense pas obligatoirement le même niveau de détail, la même origine.

Remarques sur l'exemple fourni en commentaire plus haut : 
- L'attribut "text" n'est pas ici pour précision l'origine du code, selon la définition de FHIR c'est "Plain text representation of the concept", un texte claire et compréhensible pour un humain du concept 
- Le "display" est "Representation defined by the system" c'est le libellé qui accompagne le code, certes le code n'est pas inscrit comme obligatoire dans FHIR en revanche le display n'est pas un texte libre, on est dans le cadre ici d'un élément Coding, donc d'élément défini dans une terminologie. 

Ce que je pourrais envisager en utilisant uniquement "condition" : 

![image](https://github.com/ansforge/IG-essais-cliniques/assets/122790741/4ddcffad-0e52-4658-9136-e96946664fe3)

A mon sens, l'inconvénient de cette solution, c'est que si nous avons les 2 informations, nous aurons 2 instances de condition alors qu'il n'y a qu'1 pathologie étudiée et les 2 instances n'ont pas la même granularité.

**Comment by paulineheurtebise** [comment]
Weekly 18/09 : creuser la possibilité de slicer "condition" pour mettre MedDRA et le texte libre. -> discriminant ?

**Comment by paulineheurtebise** [comment]
J'ai cherché pour les discriminateurs pour le slice. 
Je pense que la seule possibilité est un slice sur l'id.

**Comment by sdemeyANS** [comment]
branche en cours pour répondre à cette issie  https://github.com/ansforge/IG-fhir-essais-cliniques/tree/sd-supprimer-lextension-eclaire-condition-details
et preview disponible ici https://ansforge.github.io/IG-fhir-essais-cliniques/ig/sd-suppr-extension-eclaire-condition-details-and-new-slice/StructureDefinition-eclaire-researchstudy.html

**Comment by sdemeyANS** [comment]
@cbihanANS on peut utiliser MedDRA et le véhiculer vu que c'est sous licence ?

**Comment by paulineheurtebise** [comment]
Weekly 09/10 : Ne doit pas permettre d'avoir toutes les informations de MedDRA pour un utilisateur qui n'a pas la licence. 
Pas de contradiction par rapport à notre utilisation. ECLAIRE porte la licence sui permet de consommer l'information.

**Comment by sdemeyANS** [comment]
traité https://ansforge.github.io/IG-fhir-essais-cliniques/ig/main/

**Comment by sdemeyANS** [comment]
Pour info @NerOcrO et @paulineheurtebise et @nriss
en construisant l'exemple pour l'issue https://github.com/ansforge/IG-fhir-essais-cliniques/issues/38 j'ai un doute sur le fait que le slicing construit réponde bien au besoin. Du coup je réouvre cette issue pour investiguer
