### ISSUE TITLE
Estimation - Ajout données

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-essais-cliniques#74]
## Description du problème
Estimer le travail à réaliser sur les données qui seront ajoutées à l'avenir (2024?) : 
- quelles données sont natives FHIR ? 
- quelles données sont déjà mappées ?
- quelles données sont de futures extensions ? 

## Fichier•s concerné•s

[variablessiriph2g-eclaire-sante.fr-Leem-05 10 2023.xlsx](https://github.com/ansforge/IG-fhir-essais-cliniques/files/12916953/variablessiriph2g-eclaire-sante.fr-Leem-05.10.2023.xlsx)

## Solution proposée
NA - Estimation du RAF

**Comment by paulineheurtebise** [comment]
Weekly 16/10 : Identifié par Audrey des champs qui peuvent être plus facile à mapper : 

- Date of registration 
- Source of monetary support

Question ouverte : 
- Statut du recrutement : automatiser vis à vis des dates prévisionnelles de recrutement. Le consommateur vient le récupérer et a pas besoin de le calculer ?

**Comment by paulineheurtebise** [comment]
Natif R4 : 
- Durée de la participation à l'essai clinique --> Group.characteristic.period ? Est ce que cela correspond au besoin fonctionnel ?
- Completion date --> ResearchStudy.period.end (présent en R4 et R5) ou Peut etre rapproché en R5 de progressStatus ?

Pas natif FHIR ni en R4 ni en R5 : 
- Date of Registration in Primary Registry (Date d'inscription au registre principal) -> Extension à créer type date Time
- IPD sharing statement -> Extension à créer type Complex = Plan to share IPD + Plan description
- Intervention / treatment  ? 
- - Study plan - design of the study ?

Pas natif en R4 et existe en R5 : 
- Brief summary --> Extension à créer à l'image de l'attribut R5 descriptionSummary
- Statut du recrutement --> Peut etre rapproché en R5 de progressStatus ? 
- Publications about the study  --> Extension à créer à l'image de l'attribut en R5 relatedArtifact
- Ethics Review (Examen éthique) -->Peut etre rapproché en R5 de associatedParty ?
- Source(s) of Monetary or Material Support --> Peut etre rapproché en R5 de associatedParty ?
- Conséquences principales (primary outcomes) --> Peut etre rapproché en R5 de outcomeMeasure ?
- Conséquences secondaires (secondary outcomes) --> Peut etre rapproché en R5 de outcomeMeasure ?
- Summary results --> Réference vers une autre ressource ? A vérifier si ressource correspondante ?

**Comment by sdemeyANS** [comment]
@NerOcrO et @cbihanANS pour info

**Comment by sdemeyANS** [comment]
@paulineheurtebise ont pourra en profiter pour mettre en œuvre cette solution proposée par la communauté https://github.com/ansforge/IG-fhir-essais-cliniques/issues/91

**Comment by sdemeyANS** [comment]
> Natif R4 :
> 
> * Durée de la participation à l'essai clinique --> Group.characteristic.period ? Est ce que cela correspond au besoin fonctionnel ?
A valider avec Audrey ?

> * Completion date --> ResearchStudy.period.end (présent en R4 et R5) ou Peut etre rapproché en R5 de progressStatus ?
A valider avec Audrey  et @cbihanANS ?
> 
> Pas natif FHIR ni en R4 ni en R5 :
> 
> * Date of Registration in Primary Registry (Date d'inscription au registre principal) -> Extension à créer type date Time
> * IPD sharing statement -> Extension à créer type Complex = Plan to share IPD + Plan description
> * Intervention / treatment  ?
> * Study plan - design of the study ?

A analyser / valider
> 
> Pas natif en R4 et existe en R5 :
> 
> * Brief summary --> Extension à créer à l'image de l'attribut R5 descriptionSummary
> * Statut du recrutement --> Peut etre rapproché en R5 de progressStatus ?
> * Publications about the study  --> Extension à créer à l'image de l'attribut en R5 relatedArtifact
> * Ethics Review (Examen éthique) -->Peut etre rapproché en R5 de associatedParty ?
> * Source(s) of Monetary or Material Support --> Peut etre rapproché en R5 de associatedParty ?
> * Conséquences principales (primary outcomes) --> Peut etre rapproché en R5 de outcomeMeasure ?
> * Conséquences secondaires (secondary outcomes) --> Peut etre rapproché en R5 de outcomeMeasure ?
> * Summary results --> Réference vers une autre ressource ? A vérifier si ressource correspondante ?
A valider et à traiter de la manière suivante https://www.hl7.org/fhir/versions.html#extensions
ch #94

**Comment by LucChattyFyrstain** [comment]
Hello ! je me permet d'intervenir vu que je suis sur un sujet similaire en ce moment : 
> Pas natif FHIR ni en R4 ni en R5 :
> 
> * Date of Registration in Primary Registry (Date d'inscription au registre principal) -> Extension à créer type date Time
> * IPD sharing statement -> Extension à créer type Complex = Plan to share IPD + Plan description
> * Intervention / treatment  ?
> * Study plan - design of the study ?

Date of Registration in Primary Registry => R5 progressStatus avec un status (approved ? custom ?)
IPD sharing statement => R4/R5 relatedArtifact slicing avec une ressource Consent de type IPD à profiler (à mettre en contained ?)
intervention / treatment => si traitement du protocole à mettre dans le plandefinition du champ protocol.
studyplan => dans le plandefinition du champ protocol

Dispo pour en discuter si besoin.
cdt

**Comment by sdemeyANS** [comment]
dans l'analyse il faudra prévoir du rework en 2024, notamment sur les extensions existantes dans l'IG versus l'intégration de https://www.hl7.org/fhir/researchstudy-definitions.html#ResearchStudy.associatedParty présent en R5 (étude en cours)

**Comment by sdemeyANS** [comment]
> Hello ! je me permet d'intervenir vu que je suis sur un sujet similaire en ce moment :
> 
> > Pas natif FHIR ni en R4 ni en R5 :
> > 
> > * Date of Registration in Primary Registry (Date d'inscription au registre principal) -> Extension à créer type date Time
> > * IPD sharing statement -> Extension à créer type Complex = Plan to share IPD + Plan description
> > * Intervention / treatment  ?
> > * Study plan - design of the study ?
> 
> Date of Registration in Primary Registry => R5 progressStatus avec un status (approved ? custom ?) IPD sharing statement => R4/R5 relatedArtifact slicing avec une ressource Consent de type IPD à profiler (à mettre en contained ?) intervention / treatment => si traitement du protocole à mettre dans le plandefinition du champ protocol. studyplan => dans le plandefinition du champ protocol
> 
> Dispo pour en discuter si besoin. cdt

Bonjour @LucChattyFyrstain 

Pour info on a créé des issues pour séparé les sujets et le traitement des demandes.

Pour :

- Date of Registration in Primary Registry on a proposé cette modélisation par rapport au projet Eclaire #105 
- IPD sharing statement le sujet est ouvert ici #106 
- intervention / treatment le sujet est ouvert ici #107 
- studyplan le sujet est ouvert ici #108

**Comment by sdemeyANS** [comment]
issue séparées en plusieurs:

- #100 
- #105 
- #106 
- #107
- #108 
- #109 
- #110
- #111 
- #112 
- #113
