### ISSUE TITLE
CS Regulation code - Code IC-Cas-1 à retirer

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-essais-cliniques#75]
## Description du problème
Code IC-Cas-1 ne fait pas partie du code system Regulation code.

## Fichier•s concerné•s
https://ansforge.github.io/IG-fhir-essais-cliniques/ig/main/CodeSystem-eclaire-regulation-code-code-system.html
Impact sur le VS : https://ansforge.github.io/IG-fhir-essais-cliniques/ig/main/ValueSet-eclaire-category-vs.html

## Solution proposée
Retirer le code IC-Cas-1 qui ne fait pas partie du code system.

**Comment by sdemeyANS** [comment]
Bien vu! je corrige cela rapidement
