### ISSUE TITLE
Ajouter une valeur dans le code system eclaire-reglementation-precision-code-system

### ISSUE THREAD

**Issue by NerOcrO** [ansforge/IG-fhir-essais-cliniques#86]
## Description du problème
On vient de s'apercevoir qu'il manque une valeur dans eclaire-reglementation-precision-code-systemeclaire-reglementation-precision-code-system`

## Solution proposée
Ajouter :
code : EP-Cas-3
display : EP-Cas 3 (DM)

**Comment by sdemeyANS** [comment]
Effectivement elle n'était pas dans la liste de l'issue #59 
IC-Cas 1 (DM)
IC-Cas 2 (DM)
IC-Cas 3 (DM)
IC-Cas 4.1 (DM)
IC-Cas 4.2 (DM)
IC-Cas 4.3 (DM)
IC-Cas 4.4 (DM)
EP-Cas 1 (DM)
EP-Cas 2 (DM)

Catégorie 1 (JARDE)
Catégorie 2 (JARDE)
Catégorie 3 (JARDE)
Catégorie 3 questionnaire (JARDE)
Dérogation à l’obligation d’information (JARDE)

un essai clinique à faible intervention (CTIS)
un essai clinique (CTIS)

Je l'ajoute
