### ISSUE TITLE
Extensions françaises inutiles

### ISSUE THREAD

**Issue by LucChattyFyrstain** [ansforge/IG-fhir-essais-cliniques#91]
## Description du problème
Bonjour, je suis tombé sur cet IG qui me semble assez prometteur. Un bémol cependant sur le choix de la R4 sur la partie ResearchStudy qui fait partie des ressources ayant beaucoup évolué en R5. On retrouve d'ailleurs la quasi-totalité des besoins pour lesquels vous avez réalisé des extensions couverts : https://www.hl7.org/fhir/researchstudy.html
Vu l'écosystème français, le choix de la R4 peut se comprendre, mais il vaudrait mieux utiliser les extensions standard HL7 pour les éléments que l'on retrouve en R5, je ne sais pas ce que tu en penses @nriss ?

## Fichier•s concerné•s
StructureDefinition/extensions

## Solution proposée
il vaudrait mieux utiliser les extensions standard HL7 pour les éléments que l'on retrouve en R5

**Comment by sdemeyANS** [comment]
Bonjour,
Merci pour votre intérêt pour cet IG.
Il est encore assez « jeune » et comme indiqué il a été réalisé dans le cadre d’un MVP.
Au lancement de l’IG on s’est effectivement posé la question R4 ou R5.
Nous sommes effectivement restés sur R4 par rapport à l’écosystème et pour répondre au délai du projet.
Nous en avons d’ailleurs parlé lors de notre présentation à la JFI en septembre.

Ensuite, en itérant, nous avons effectivement constaté que des éléments absents en R4 et présents en R5 pouvez répondre à nos besoins.
Nous avons alors tenté de mimer R5 en créant des extensions comme [ECLAIRELabel - Essais CLiniques Accessibles Interconnectés pour la Recherche ouverts à l'Ecosystème v0.2.0 (esante.gouv.fr)](https://interop.esante.gouv.fr/ig/fhir/eclaire/StructureDefinition-eclaire-label.html) qui correspond à [ResearchStudy - FHIR v5.0.0 (hl7.org)](https://hl7.org/fhir/researchstudy-definitions.html#ResearchStudy.label) en R5.
L’objectif étant de faciliter une éventuelle migration en R5 le cas échéant.
En lisant votre remarque je me suis rendu compte que cette information est en commentaire dans le FSH mais devrait explicitement être indiquée dans la description de l’extension. Je note ce point d’amélioration que nous allons traiter rapidement.
Nous allons aussi faire repasse sur les autres extensions.

**Comment by nriss** [comment]
Hello Luc,

Carrément d'accord pour utiliser les extensions standard lorsque c'est possible. 
Tu en as identifié certaines que l'on a raté ? S'il en existe qui font exactement ce dont on a besoin, clairement partant pour les utiliser :)

**Comment by LucChattyFyrstain** [comment]
Hello @sdemeyANS, @nriss, 
Il y a un mécanisme officiel pour récupérer des champs d'une ressource d'une version supérieure :

L'url canonique à utiliser est [http://hl7.org/fhir/5.0/StructureDefinition/extension-[path](http://hl7.org/fhir/5.0/StructureDefinition/extension-%5bpath)], (il y a un package où elles sont défines)

par exemple http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.composition utilisée ici : https://build.fhir.org/ig/hl7-eu/laboratory/StructureDefinition-DiagnosticReport-eu-lab.html

C'est un mécanisme très intéressant pour compenser les manques de la R4 quand on veut les fonctionnalités de la R5 dans un écosystème R4 et ça permet une migration ultérieure plus facile / une coexistence R4/R5 avec des conversions plus automatiques.

Si vous avez un soucis pour les implémenter dites moi je regarderai. Je suis dans un projet EDS en ce moment, je vais avoir besoin de la ResearchStudy à un moment donné de toute façon.

**Comment by nriss** [comment]
Génial on avait pas identifié ça !! Tu sais où est-ce que c'est documenté ? 
On va voir côté implem si le planning nous permet de modifier, et dans tous les cas on met ça en place pour nos prochains profils :)

**Comment by LucChattyFyrstain** [comment]
https://www.hl7.org/fhir/versions.html#extensions

super !

**Comment by sdemeyANS** [comment]
Merci je teste cela :)

**Comment by sdemeyANS** [comment]
Bonjour,
Je clos cette issue et je la référencerai dans les issues qui vont en découler comme #94
