### ISSUE TITLE
modification extension EclaireLabel

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-fhir-essais-cliniques#94]
## Description du problème
Mettre en oeuvre la solution proposée par la communauté cf https://github.com/ansforge/IG-fhir-essais-cliniques/issues/91

## Fichier•s concerné•s
ResearchStudy et extension EclaireLabel

## Solution proposée
Mise en œuvre de la solution détaillée dans https://github.com/ansforge/IG-fhir-essais-cliniques/issues/91
exemple https://github.com/hl7-eu/laboratory/blob/master/input/fsh/profiles/diagnosticReport-lab.fsh

Impact évalué à date:

- [x] modification StructureDefinition
- [x] modification mapping
- [x] au niveau de l'impementation modification Url de l'extension

**Comment by paulineheurtebise** [comment]
Modification du mapping proposé

**Comment by sdemeyANS** [comment]
Bonjour @NerOcrO
Voici ce que nous avons modifié pour l'extension complexe EclaireLabel afin de mieux "l'identifier" comme étant un élément provenant de R5
preview : https://ansforge.github.io/IG-fhir-essais-cliniques/ig/sd-modification-extension-eclairelabel-to-R5/StructureDefinition-eclaire-researchstudy.html

Sauf erreur, les impacts côté dev sont les suivants:
1. modification de l'URL de l'extension
2. changement url extension labelValue=> value et labelType => type

Avant de merge, comme convenu, je souhaite valider avec vous ces impacts et le fait que cela peut être pris en compte.

D'avance, merci pour votre retour

**Comment by sbedeau** [comment]
Ok pour nous
