### ISSUE TITLE
Références vers profils ECLAIRE

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-essais-cliniques#98]
## Description du problème

Dans le profil [ECLAIREResearchStudy](https://ansforge.github.io/IG-fhir-essais-cliniques/ig/main/StructureDefinition-eclaire-researchstudy.html), si je ne me trompe pas la référence vers `Group` via `enrollment` devrait pointer vers le profil [ECLAIREGroup](https://ansforge.github.io/IG-fhir-essais-cliniques/ig/main/StructureDefinition-eclaire-group.html) mais ce n'est pas le cas. Même chose pour la référence vers `Location` via `site`, le profil ECLAIRE n'est pas utilisé.

## Fichier•s concerné•s

[ECLAIREResearchStudy.fsh](https://github.com/ansforge/IG-fhir-essais-cliniques/blob/main/input/fsh/StructureDefinition/profiles/ECLAIREResearchStudy.fsh)

## Solution proposée

Ajouter les références vers les profils ECLAIRE dans le profil ECLAIREResearchStudy.

**Comment by nriss** [comment]
Si les profils ECLAIREGroup, ECLAIRELocation, EclaireResearchStudy sont bien utilisés, il n'y a à priori pas de nécessité de changer l'implémentation étant donné que cette contrainte est déjà respectée
