### ISSUE TITLE
[Ajout données] - Completion date

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-essais-cliniques#99]
Dans l'issue #74, la donnée "completion date" avait été identifiée comme potentiellement native R4 via `ResearchStudy.period.end`.
Il s'agit de la date à laquelle l'essai se termine (toutes les informations sont récupérées). C'est une date est prévisionnelle, qui est normalement connu au début de l'essai (quand la demande est faite au comité éthique), elle peut être déplacée. 
Suite à ces précisions, deux solutions (au moins) sont envisageables : 
* Utiliser ResearchStudy.period.end en précisant dans la définition qu'il s'agit d'une date prévisionnelle 
  * Avantage : natif
  * Inconvénient : peut poser problème si on a également une date réelle par la suite 
* Créer une extension 
  * Avantage : permet de pouvoir également renseigner une date réelle 
  * Inconvénient : pas natif

**Comment by audreyMoisan** [comment]
Pour la completion date, dans les faits une nouvelle date est sujet à dérogation car cela doit demander une nouvelle validation des CPP. Ce n'est donc pas la majorité des cas (c'est dans le cas ou l'essai a pris beaucoup de retard, pb de recrutement par exemple),  de plus le champ n'est pas encore crée dans le SIRIPH2G donc on peut imaginer configurer le champ en fonction de FHIR (dans la mesure du possible si ça correspond aux usages des déposants.) 
Nous pouvons peut être partir sur du natif dans un premier temps ?

**Comment by sly-kereval** [comment]
La proposition retenue est d'utiliser ResearchStudy.period.end.

Preview disponible : https://ansforge.github.io/IG-fhir-essais-cliniques/ig/ajout-donnees-mapping/mapping.html
